HW4 Task01
Angelina151612/epam_python pull request #22
Opened 2020-11-16 02:04 UTC by Angelina151612

2020-11-16 23:18 UTC, Cjkjvfnby requested changes

2020-11-16 23:18 UTC, Cjkjvfnby commented on hw/hw_04_task_01.py
> +            if 1 <= num < 3:
You can simplify return value

2020-11-17 20:12 UTC, Angelina151612 commented on hw/hw_04_task_01.py
> +            if 1 <= num < 3:
Done

2020-11-17 21:35 UTC, Cjkjvfnby approved these changes

2020-11-18 18:48 UTC, merged