HW9 Task02
Angelina151612/epam_python pull request #35
Opened 2020-12-16 23:43 UTC by Angelina151612

2020-12-17 20:42 UTC, Cjkjvfnby requested changes
Do both versions work in the same way?

2020-12-17 20:42 UTC, Cjkjvfnby commented on hw/hw_09_task_02.py
> +        if exc_type == self.exception:
Can we inline it?

2020-12-19 22:38 UTC, Angelina151612 commented
> Do both versions work in the same way?

I don't really understand you. It's different structures, so they can work in different ways, can't they? They have the same behavior in tests.

2020-12-19 23:35 UTC, Cjkjvfnby requested changes
Please add a test for both cases:

```
with ... (Exception):
   raise IndexError()
```

2020-12-19 23:35 UTC, Cjkjvfnby commented on test/test_02_hw_09.py
> +        [][2]
What does this code do?

It raises IndexError.

Can we read Python code as an English phrase?  Yes! 
 
```python
raise IndexError()
```

2020-12-20 16:21 UTC, Angelina151612 commented
Ok, I got it. "Ecxept"  also catches all subclasses. We should also check it in class.

2020-12-20 17:58 UTC, Cjkjvfnby approved these changes

2020-12-22 18:01 UTC, merged