HW2 Task03
Angelina151612/epam_python pull request #9
Opened 2020-11-07 20:57 UTC by Angelina151612

2020-11-07 23:41 UTC, Cjkjvfnby requested changes

2020-11-07 23:41 UTC, Cjkjvfnby commented on Homework2/Task03/task03.py
> +    for comb in itertools.product(*args):
The whole function can be oneliner.

2020-11-08 21:38 UTC, Cjkjvfnby commented on Homework2/Task03/task03.py
> +    return [list(comb) for comb in itertools.product(*args)]
Can you solve it without itertools?

2020-11-09 14:45 UTC, Angelina151612 commented on Homework2/Task03/task03.py
> +    return [list(comb) for comb in itertools.product(*args)]
I can do something like this.
```
        def combinations(*args: List[Any]) -> List[List]:
            result = [[]]
            for arg in args:
                result = [x + [y] for x in result for y in arg]
            return result
```

2020-11-09 21:01 UTC, Cjkjvfnby commented on Homework2/Task03/task03.py
> +    return [list(comb) for comb in itertools.product(*args)]
Please do something and pass the tests.

2020-11-09 21:02 UTC, Cjkjvfnby requested changes
`product` is nice but it kind of cheating lets solve this task without it.

2020-11-10 17:27 UTC, Cjkjvfnby approved these changes

2020-11-10 17:30 UTC, merged